#!/usr/bin/env python3
"""Build outputs/act_one_svo.pdf.

A Subject-Verb-Object breakdown of Act One: every speech reduced to a single
simple sentence (one subject, one verb, one object), with the original line
shown beneath for reference.

Inputs (both relative to the repo root):
  data/act_one_speeches.json  -- {n, speaker, text}  (generated by _extract_act_one.py)
  data/act_one_svo.json       -- {n, svo}

Output:
  outputs/act_one_svo.pdf

Requires: playwright (+ chromium).  Run from the repo root:  python scripts/build_act_one_svo.py
"""
from pathlib import Path
import json, html
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parent.parent
speeches = json.loads((ROOT / "data" / "act_one_speeches.json").read_text(encoding="utf-8"))
svos = {d["n"]: d["svo"] for d in json.loads((ROOT / "data" / "act_one_svo.json").read_text(encoding="utf-8"))}


def clean(t: str) -> str:
    """Unescape source entities, drop a leading stray '.', normalise, re-escape for HTML."""
    t = html.unescape(t)
    t = t.strip()
    if t.startswith('. '):
        t = t[2:]
    elif t.startswith('.'):
        t = t[1:].strip()
    return html.escape(t)


rows = []
for s in speeches:
    n = s["n"]
    speaker = html.escape(s["speaker"])
    svo = html.escape(svos.get(n, "\u2014"))
    original = clean(s["text"])
    rows.append(f"""
    <div class="row">
      <div class="num">{n}</div>
      <div class="body">
        <div class="speaker">{speaker}</div>
        <div class="svo">{svo}</div>
        <div class="orig">&ldquo;{original}&rdquo;</div>
      </div>
    </div>""")

ROWS = "\n".join(rows)

HTML = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>Act One — Subject / Verb / Object</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;1,400&family=Cormorant+Garamond:wght@400;500;600&family=Cormorant+Unicase:wght@500;600;700&display=swap" rel="stylesheet">
<style>
  :root {{ --paper:#efe6cf; --ink:#2a201a; --ink-soft:#6b5b48; --accent:#8b3a3a; --rule:rgba(42,32,26,0.18); }}
  @page {{ size: A4; margin: 20mm 18mm 20mm 18mm; }}
  *,*::before,*::after {{ box-sizing: border-box; }}
  html, body {{ background: var(--paper); color: var(--ink);
    font-family:'EB Garamond','Georgia',serif; font-size: 11pt; line-height: 1.5; margin:0; padding:0; }}

  /* Cover */
  .cover {{ height: 250mm; display:flex; flex-direction:column; justify-content:center; text-align:center; page-break-after: always; }}
  .cover .eyebrow {{ font-family:'Cormorant Unicase',serif; font-weight:600; letter-spacing:0.34em; font-size:11pt; text-transform:uppercase; color:var(--accent); margin-bottom:14mm; }}
  .cover h1 {{ font-family:'Cormorant Garamond',serif; font-weight:500; font-size:34pt; line-height:1.06; margin:0 0 3mm 0; }}
  .cover .italian {{ font-style:italic; font-size:13pt; color:var(--ink-soft); margin:0 0 16mm 0; }}
  .cover .rule {{ width:52mm; height:1px; background:var(--rule); margin:6mm auto; }}
  .cover .sub {{ font-family:'Cormorant Garamond',serif; font-size:20pt; letter-spacing:0.04em; margin:0 0 3mm 0; }}
  .cover .note {{ font-style:italic; color:var(--ink-soft); font-size:11.5pt; max-width:120mm; margin:0 auto 12mm; line-height:1.6; }}
  .cover .prod {{ font-size:11pt; letter-spacing:0.06em; }}
  .cover .place {{ font-style:italic; color:var(--ink-soft); font-size:10.5pt; }}

  .how {{ max-width:150mm; margin:0 auto 10mm; padding:5mm 6mm; border:1px solid var(--rule); border-radius:1mm; background:rgba(42,32,26,0.03); font-size:10pt; color:var(--ink-soft); line-height:1.6; }}
  .how strong {{ color:var(--ink); }}

  h2.parthead {{ font-family:'Cormorant Unicase',serif; font-weight:600; font-size:10pt; letter-spacing:0.2em; text-transform:uppercase; color:var(--accent); margin:0 0 6mm 0; text-align:center; }}

  .row {{ display:flex; gap:6mm; padding:3mm 0; border-bottom:1px solid var(--rule); page-break-inside:avoid; }}
  .num {{ flex:0 0 12mm; text-align:right; font-variant-numeric:tabular-nums; color:var(--accent); font-weight:600; font-size:10pt; padding-top:1.5mm; }}
  .body {{ flex:1; }}
  .speaker {{ font-family:'Cormorant Unicase',serif; font-weight:600; font-size:8pt; letter-spacing:0.14em; text-transform:uppercase; color:var(--ink-soft); margin-bottom:1mm; }}
  .svo {{ font-family:'Cormorant Garamond',serif; font-size:15pt; font-weight:500; color:var(--ink); line-height:1.25; }}
  .orig {{ font-style:italic; color:var(--ink-soft); font-size:9.5pt; margin-top:1.5mm; line-height:1.45; }}

  .footer-note {{ margin-top:10mm; padding-top:4mm; border-top:1px solid var(--rule); text-align:center; font-style:italic; font-size:9pt; color:var(--ink-soft); }}
</style>
</head><body>

  <section class="cover">
    <p class="eyebrow">Act One &middot; Subject &middot; Verb &middot; Object</p>
    <h1>Six Characters<br>in Search of an Author</h1>
    <p class="italian">Sei personaggi in cerca d'autore</p>
    <div class="rule"></div>
    <p class="sub">The Action of Act One, Line by Line</p>
    <p class="note">Every speech in Act One reduced to a single simple sentence &mdash; one subject, one verb, one object &mdash; with the original line printed beneath it.</p>
    <p class="prod">A Village Players production</p>
    <p class="place">Lausanne</p>
  </section>

  <div class="how">
    <p style="margin:0 0 3mm 0;"><strong>How to read this.</strong> Each entry is one speech from Act One, in performance order. The bold line is the <strong>action</strong> of the speech in the plainest form &mdash; who does what to what. The italic line below is the actual dialogue, for reference.</p>
    <p style="margin:0;">{len(speeches)} speeches in all.</p>
  </div>

  <h2 class="parthead">Act One &mdash; The Action, Speech by Speech</h2>

  {ROWS}

  <p class="footer-note">Village Players &middot; Lausanne &nbsp;&middot;&nbsp; Act One &middot; Subject-Verb-Object breakdown</p>

</body></html>
"""

TMP = ROOT / "outputs" / "_act_one_svo_tmp.html"
TMP.parent.mkdir(exist_ok=True)
TMP.write_text(HTML, encoding="utf-8")

OUT = ROOT / "outputs" / "act_one_svo.pdf"
print(f"Rendering Act One SVO ({len(speeches)} speeches) -> {OUT.name} ...")
with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto(f"file://{TMP.resolve()}", wait_until="networkidle", timeout=60000)
    page.wait_for_timeout(1000)
    page.pdf(path=str(OUT), format="A4",
             margin={"top": "20mm", "right": "18mm", "bottom": "20mm", "left": "18mm"},
             print_background=True, prefer_css_page_size=True)
    browser.close()

TMP.unlink(missing_ok=True)
print(f"Done: {OUT} ({OUT.stat().st_size:,} bytes)")
